# gynter.github.io - Homepage of Günter Kits

# For Jekyll configuration options please see 
# http://jekyllrb.com/docs/configuration/

# Paths.
data_source:    ./_data
collections:
  projects:
    output: false

# Handling reading.
exclude:
  - .bundle
  - .gitignore
  - .sass-cache
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - vendor
encoding:       utf-8
markdown_ext:   markdown,mkdown,mkdn,mkd,md
textile_ext:    textile

# Content handling.
show_drafts:    null
lsi:            false
limit_posts:    0
future:         true
markdown:       kramdown
highlighter:    pygments

# Serving.
detach:     false
port:       4000
host:       127.0.0.1
baseurl:    ""
url:        "http://kyber.kits.ee"

# Outputting.
permalink:          pretty
paginate:           3
paginate_path:
  - en/page:num
  - et/leht:num
paginate_filter:
  - name: language
    value: "en_US"
  - name: language
    value:
      - "et_EE"
      - "en_US"
paginator_offset:   2
timezone:           UTC

# Posts' and pages' defaults.
defaults:
  -
    # This is the global scope (global defaults). All values here can
    # be overridden in specific post or page.
    scope:
      path: ""
    values:
      # Page title prefix.
      title_prefix: kyberkits
      # Page title.
      title: Home
      # Author for pages and posts.
      author: Günter Kits
      # Contact e-mail for pages and posts.
      email: kyber@kits.ee
      # Default language.
      language: en_US
      # Preferred feed standard. Possible values are: atom, rss or null.
      # If set to null then no feed links are present, but feeds can
      # still be accessed directly via /feed/atom or /feed/rss.
      feed: rss2
      # Path to icon for feed (Atom standard only).
      feed_icon: null
      # Path to logo for feed (recommended w/h aspect ratio is 2:1).
      feed_logo: null
      # How many posts will be shown in the feed.
      feed_posts_limit: 10
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
